def project = 'genie.trafficgen'


pipeline {
    agent {
        label 'linux'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
    }
    stages {
        stage("Install pyATS/Genie and make develop") {
            steps {
                sh """
                    env
                    pip list
                    pip freeze
                    export PIP_DOWNLOAD_CACHE=/scratch/pip_download_cache
                    export LC_ALL=C.UTF-8
                    /scratch/pyadm/.pyenv/versions/3.8.8/bin/python -m venv genietrafficgen-env
                    . genietrafficgen-env/bin/activate
                    pip3 install --upgrade pip setuptools
                    pip3 install --no-cache-dir wheel pytest pytest-xdist ixnetwork_restpy
                    pip3 install git+https://bitbucket-eng-sjc1.cisco.com/bitbucket/scm/devxtgen/trex_hltapi.git
                    pip3 install --no-cache-dir -i http://pyats-pypi.cisco.com/simple --trusted-host pyats-pypi.cisco.com cisco-distutils ats[full]
                    cd $WORKSPACE
                    make develop
                    env
                    pip list
                    pip freeze
                """
            }
        }

        stage("Run compileAll") {
            steps {
                sh """
                . genietrafficgen-env/bin/activate
                compileAll --path=src
                """
            }
        }


        stage("Run tests") {
            steps {
                sh """
                . genietrafficgen-env/bin/activate
                cd tests
                py.test -v .
                """
            }
        }
    }
    post {
        cleanup {
            cleanWs()
        }
    }
}
